### ISSUE TITLE
KeyError: 'trans_result'

### ISSUE THREAD

**Issue by LL-MF** [Hypdncy/NessusToReport#1]
2021-05-20 15:34:30,347 - root - INFO - 开始初始化数据
2021-05-20 15:34:30,347 - root - INFO - ---开始读取数据     
2021-05-20 15:34:30,355 - root - INFO - ----漏洞种类总数：27
2021-05-20 15:34:30,355 - root - INFO - ----漏洞主机总数：3 
2021-05-20 15:34:30,355 - root - INFO - ---开始翻译数据     
Traceback (most recent call last):
  File "f:/Tools工具/nessus报告生成/main.py", line 45, in <module>
    h = Handle(args.docxtype)
  File "f:\Tools工具\nessus报告生成\modle\handle.py", line 54, in __init__
    TranBaidu(self.LOOPHOLES).run()
  File "f:\Tools工具\nessus报告生成\modle\common\translate\base.py", line 83, in run
    self._tran()
  File "f:\Tools工具\nessus报告生成\modle\common\translate\baidu.py", line 87, in _tran
    self.LOOPHOLES[plugin_id][type_cn] = resinfo["trans_result"][0]["dst"]
KeyError: 'trans_result'

API配置在const.py
translate_baidu_appid = "2021xx"
translate_baidu_secret = "aOuxx"

**Comment by Hypdncy** [comment]
这是由于百度API有翻译速度限制导致的，可以尝试更改协程并发数 cnf/const.py 中translate_asyncios参数，将其减半或者更改为1

**Comment by moonmistake** [comment]
请选择：高级版。
默认开通的版本会有限制，打印日志可以看出：错误代码：54003,访问频率受限 | 请降低您的调用频率，或进行身份认证后切换为高级版/尊享版
参考百度翻译API的文档：https://fanyi-api.baidu.com/doc/21

**Comment by Hypdncy** [comment]
我使用的是高级版，QPS为10，目前在500M电信带宽下，是可以正常翻译的
高级版也是有免费字数的，可以尝试升级下

**Comment by LL-MF** [comment]
感谢，在我将版本选择高级版和降低translate_asyncios值后已成功执行。但抛出其他异常
Traceback (most recent call last):
  File "f:/Tools工具/nessus报告生成/main.py", line 46, in <module>
    h.run()
  File "f:\Tools工具\nessus报告生成\modle\handle.py", line 95, in run
    func_type_run[self.docxtype]()
  File "f:\Tools工具\nessus报告生成\modle\handle.py", line 63, in run_hosts
    DataHosts(self.LOOPHOLES).run()
  File "f:\Tools工具\nessus报告生成\modle\data\hosts.py", line 83, in run
    super(DataHosts, self).run()
  File "f:\Tools工具\nessus报告生成\modle\data\base.py", line 93, in run
    self._gen_data_systems()
  File "f:\Tools工具\nessus报告生成\modle\data\base.py", line 81, in _gen_data_systems
    next(f)
File "C:\Users\PC\AppData\Local\Programs\Python\Python37-32\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte

是否需要修改代码中的utf8编码修改为gbk或其他？或是如何处理

**Comment by LL-MF** [comment]
> 
> 
> 感谢，在我将版本选择高级版和降低translate_asyncios值后已成功执行。但抛出其他异常
> Traceback (most recent call last):
> File "f:/Tools工具/nessus报告生成/main.py", line 46, in
> h.run()
> File "f:\Tools工具\nessus报告生成\modle\handle.py", line 95, in run
> func_type_runself.docxtype
> File "f:\Tools工具\nessus报告生成\modle\handle.py", line 63, in run_hosts
> DataHosts(self.LOOPHOLES).run()
> File "f:\Tools工具\nessus报告生成\modle\data\hosts.py", line 83, in run
> super(DataHosts, self).run()
> File "f:\Tools工具\nessus报告生成\modle\data\base.py", line 93, in run
> self._gen_data_systems()
> File "f:\Tools工具\nessus报告生成\modle\data\base.py", line 81, in _gen_data_systems
> next(f)
> File "C:\Users\PC\AppData\Local\Programs\Python\Python37-32\lib\codecs.py", line 322, in decode
> (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte
> 
> 是否需要修改代码中的utf8编码修改为gbk或其他？或是如何处理

**Comment by Hypdncy** [comment]
你需要将csv的编码更改为UTF-8 ，在excel右键导出的时候可以选择，或者通过直接修改CSV文件的方式

**Comment by safebaseline** [comment]
始终报同样的错！！不管怎么调整！！
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    h = Handle(args.docxtype)
  File "D:\工具\NessusToReport-20210521\modle\handle.py", line 54, in __init__
    TranBaidu(self.LOOPHOLES).run()
  File "D:\工具\NessusToReport-20210521\modle\common\translate\base.py", line 84, in run
    self._tran()
  File "D:\工具\NessusToReport-20210521\modle\common\translate\baidu.py", line 87, in _tran
    self.LOOPHOLES[plugin_id][type_cn] = resinfo["trans_result"][0]["dst"]
KeyError: 'trans_result'
