### ISSUE TITLE
百度云的QPS限制解决方案已经提交，请更新代码重试

### ISSUE THREAD

**Issue by Hypdncy** [Hypdncy/NessusToReport#13]

**Comment by LaIMirch** [comment]
大佬，我git clone了新的代码，然后换了3个不同的网络，还是会报错- - 
C:\Users\Administrator\Desktop\NessusToReport>python main.py -t loops
2022-06-21 11:43:40,310 - root - INFO - 开始初始化数据
2022-06-21 11:43:40,310 - root - INFO - ---开始读取数据
2022-06-21 11:43:40,383 - root - INFO - ----漏洞种类总数：74
2022-06-21 11:43:40,384 - root - INFO - ----漏洞主机总数：31
2022-06-21 11:43:40,385 - root - INFO - ---开始翻译数据
2022-06-21 11:43:40,387 - root - INFO - ------翻译漏洞总数：11
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NessusToReport\main.py", line 45, in <module>
    h = Handle(args.docxtype)
  File "C:\Users\Administrator\Desktop\NessusToReport\modle\handle.py", line 57, in __init__
    TranBaidu(self.LOOPHOLES).run()
  File "C:\Users\Administrator\Desktop\NessusToReport\modle\common\translate\base.py", line 106, in run
    self.LOOPHOLES[plugin_id][type_cn] = self._analysis_cn_resinfo(resinfo)
  File "C:\Users\Administrator\Desktop\NessusToReport\modle\common\translate\baidu.py", line 87, in _analysis_cn_resinfo
    return resinfo["trans_result"][0]["dst"]
KeyError: 'trans_result'

**Comment by LaIMirch** [comment]
可以了可以了，就是数量不太对，我再研究一下

**Comment by LaIMirch** [comment]
https://zh-cn.tenable.com/plugins/nessus/131831
如果用官方文档翻译的这种方法，是否效率会更高呢，或者把官方的批量保存到本地来

**Comment by LaIMirch** [comment]
Thank you for your message, which has been added to a queuing system. You are currently in 352nd place, and can expect to receive a reply in approximately 19 weeks.

**Comment by Hypdncy** [comment]
> Thank you for your message, which has been added to a queuing system. You are currently in 352nd place, and can expect to receive a reply in approximately 19 weeks.

好想法

**Comment by Hypdncy** [comment]
> https://zh-cn.tenable.com/plugins/nessus/131831 如果用官方文档翻译的这种方法，是否效率会更高呢，或者把官方的批量保存到本地来

好想法

**Comment by Hypdncy** [comment]
已经增加该功能
