### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by liyikrad** [Hypdncy/NessusToReport#15]
配置完后执行main.py报错
TypeError: cannot unpack non-iterable NoneType object

**Comment by Hypdncy** [comment]
麻烦提供下详细报错

**Comment by Vumei** [comment]
C:\Program Files\Tools\Nessus_Report\NessusToReport-1.2>python3 main.py
2024-05-22 14:44:55,905 - root - INFO - 开始初始化数据
2024-05-22 14:44:55,905 - root - INFO - ---开始读取数据
2024-05-22 14:44:55,938 - root - INFO - ----漏洞种类总数：23
2024-05-22 14:44:55,938 - root - INFO - ----漏洞主机总数：4
2024-05-22 14:44:55,938 - root - INFO - ---开始翻译数据
2024-05-22 14:44:55,938 - root - INFO - ------翻译漏洞总数：1
0, message='', url=URL('https://www.tenablecloud.cn/plugins/nessus/192042')
Traceback (most recent call last):
  File "C:\Program Files\Tools\Nessus_Report\NessusToReport-1.2\main.py", line 48, in <module>
    h = Handle(args.docxtype, args.exceltype)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Tools\Nessus_Report\NessusToReport-1.2\modle\handle.py", line 65, in __init__
    func_translate_tools[translate_tool](self.LOOPHOLES).run()
  File "C:\Program Files\Tools\Nessus_Report\NessusToReport-1.2\modle\common\translate\base.py", line 110, in run
    for plugin_id, resinfo in cn_resinfos:
        ^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

C:\Program Files\Tools\Nessus_Report\NessusToReport-1.2>
