### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'aiautosumm01'

### ISSUE THREAD

**Issue by moonmistake** [Hypdncy/NessusToReport#2]
2021-05-21 17:35:06,100 - root - INFO - ------翻译完成
2021-05-21 17:35:06,106 - root - INFO - 开始生成漏洞排序报告
2021-05-21 17:35:06,106 - root - INFO - ---开始处理数据
Traceback (most recent call last):
  File "D:\tools\NessusToReport\main.py", line 46, in <module>
    h.run()
  File "D:\tools\NessusToReport\modle\handle.py", line 95, in run
    func_type_run[self.docxtype]()
  File "D:\tools\NessusToReport\modle\handle.py", line 75, in run_loops
    DataLoops(self.LOOPHOLES).run()
  File "D:\tools\NessusToReport\modle\data\loops.py", line 101, in run
    self._sort_and_gen_date()
  File "D:\tools\NessusToReport\modle\data\loops.py", line 89, in _sort_and_gen_date
    loop_host_ports[plugin_id] = dict(sorted(host_ports.items(), key=key))
  File "D:\tools\NessusToReport\modle\data\loops.py", line 76, in <lambda>
    return lambda x: IP(x[0]).int()
  File "D:\tools\Python39\lib\site-packages\IPy.py", line 249, in __init__
    (self.ip, parsedVersion) = parseAddress(ip, ipversion)
  File "D:\tools\Python39\lib\site-packages\IPy.py", line 1422, in parseAddress
    bytes = [int(x) for x in bytes]
  File "D:\tools\Python39\lib\site-packages\IPy.py", line 1422, in <listcomp>
    bytes = [int(x) for x in bytes]
ValueError: invalid literal for int() with base 10: 'aiautosumm01'

**Comment by Hypdncy** [comment]
loop_host_ports[plugin_id] = dict(sorted(host_ports.items(), key=key)) =>
loop_host_ports[plugin_id] = dict(sorted(host_ports.items(), key=lambda x: x[0]))

**Comment by moonmistake** [comment]
神速，可以了... @Hypdncy 
另外，能否增加各种列表以及饼图等功能？

**Comment by Hypdncy** [comment]
之前考虑过柱状图，饼图的实现，也有解决方案，但是目前项目上没有这种需求，你可以简单提下需求，我有时间开发下

**Comment by moonmistake** [comment]
简单考虑一下：
表的需求2类：
   按照系统名称的表头：IP,系统名称，漏洞级别，漏洞名称
   按照系漏洞的表头：漏洞名称  ,IP+系统名称列表，漏洞级别
柱状图，饼图这些根据以上数据，自己生成即可，不需要程序单独写个功能
多谢
