### ISSUE TITLE
nessus10.2出现以下报错，麻烦作者大大看看，附带我使用的csv文件

### ISSUE THREAD

**Issue by poetmilk** [Hypdncy/NessusToReport#32]
$ python main.py -t host
2023-03-05 22:37:27,748 - root - INFO - 开始初始化数据
2023-03-05 22:37:27,748 - root - INFO - ---开始读取数据
2023-03-05 22:37:27,760 - root - INFO - ----漏洞种类总数：65
2023-03-05 22:37:27,761 - root - INFO - ----漏洞主机总数：3
2023-03-05 22:37:27,761 - root - INFO - ---开始翻译数据
2023-03-05 22:37:27,762 - root - INFO - ------翻译漏洞总数：8
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
'trans_result'
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    h = Handle(args.docxtype)
  File "C:\PMSec\tools\vulnerability-scanner\NessusToReport-1.1.1\modle\handle.py", line 63, in __init__
    func_translate_tools[translate_tool](self.LOOPHOLES).run()
  File "C:\PMSec\tools\vulnerability-scanner\NessusToReport-1.1.1\modle\common\translate\base.py", line 110, in run
    for plugin_id, resinfo in cn_resinfos:
TypeError: cannot unpack non-iterable NoneType object
[adv_scan_75e1kc.csv](https://github.com/Hypdncy/NessusToReport/files/10892072/adv_scan_75e1kc.csv)

**Comment by Hypdncy** [comment]
是否更换了百度api的key呢，新版本自带从官网拉取信息了

**Comment by ykwiss** [comment]
我也是这个问题 咋弄啊 没用百度key
