### ISSUE TITLE
数据库问题

### ISSUE THREAD

**Issue by MatriX925** [Hypdncy/NessusToReport#38]
原有数据库老旧，导致导出的报告数据有误。
我爬取了官网信息，重建了数据库，漏洞数量为84150，麻烦作者联系我。

**Comment by 2453862397** [comment]
@Hypdncy 作者，有没有最新的数据库？ 
@MatriX925 大佬能不能分享一下

**Comment by 2453862397** [comment]
作者，有没有最新的数据库啊
大佬 @MatriX925 分享一下

**Comment by ztong116** [comment]
@MatriX925 大佬，数据库求分享

**Comment by MatriX925** [comment]
[下载链接](https://pan.baidu.com/s/1ZdW7VpgJbMcsH3-mM8Ut3A?pwd=7pyi)
23年12月8日更新的，自取吧

**Comment by himywei** [comment]
@MatriX925 大佬，提取码方便提供一下吗，感谢

**Comment by MatriX925** [comment]
链接里带提取码的吧
发自我的 iPhone 12

在 2023年12月13日，11:37，himywei ***@***.***> 写道：

﻿

@MatriX925<https://github.com/MatriX925> 大佬，提取码方便提供一下吗，感谢

**Comment by himywei** [comment]
thanks a lot

**Comment by himywei** [comment]
@MatriX925 方便提供下邮箱吗，有些问题想请教一下。

**Comment by MatriX925** [comment]
***@***.***
发自我的 iPhone 12

在 2023年12月13日，17:33，himywei ***@***.***> 写道：

﻿

@MatriX925<https://github.com/MatriX925> 方便提供下邮箱吗，有些问题想请教一下。

**Comment by himywei** [comment]
@MatriX925 怎么看不见内容，全是 ***

**Comment by MatriX925** [comment]
@himywei [qq744781748@outlook.com](qq744781748@outlook.com)

**Comment by void-ll** [comment]
[@MatriX925](https://github.com/MatriX925) 大佬能发一下脚本吗，我想把info的也爬一下

**Comment by MatriX925** [comment]
@void-ll 数据库里有info的

**Comment by hstz520** [comment]
我在翻译esxi的csv时发现还是缺少部分，我下了个sqlite expert往vuln.db插入了缺少的几条，报下面错的应该都是数据库里面缺少对应的翻译，需要自己往数据库加翻译。

PS E:\NessusToReport-master> python .\main.py
2024-04-22 15:23:27,752 - root - INFO - 开始初始化数据
2024-04-22 15:23:27,752 - root - INFO - ---开始读取数据
2024-04-22 15:23:27,760 - root - INFO - ----漏洞种类总数：3
2024-04-22 15:23:27,760 - root - INFO - ----漏洞主机总数：1
2024-04-22 15:23:27,761 - root - INFO - ---开始翻译数据
2024-04-22 15:23:27,763 - root - INFO - ------翻译漏洞总数：1
'trans_result'
'trans_result'
Traceback (most recent call last):
  File "E:\NessusToReport-master\main.py", line 48, in <module>
    h = Handle(args.docxtype, args.exceltype)
  File "E:\NessusToReport-master\modle\handle.py", line 65, in __init__
    func_translate_tools[translate_tool](self.LOOPHOLES).run()
  File "E:\NessusToReport-master\modle\common\translate\base.py", line 110, in run
    for plugin_id, resinfo in cn_resinfos:
TypeError: cannot unpack non-iterable NoneType object

**Comment by hstz520** [comment]
@MatriX925 写sql手动插入缺少翻译项太麻烦了，请教下如何爬官网最新数据库？能分享下方法吗

**Comment by MatriX925** [comment]
@hstz520 爬数据不难，难在提取加工，提供你最新的数据库吧，更新时间2024 年 4月 22 日。
链接: https://pan.baidu.com/s/1EbBAwrH-0QDatMRT9l6x8w?pwd=g9ub 提取码: g9ub

**Comment by 1466961372** [comment]
为什么我的读取是0 呢，报告里面也是空的
![image](https://github.com/Hypdncy/NessusToReport/assets/126546640/0bd9ab00-b231-4527-b66a-f2e8233ca7ea)

**Comment by xiaogezainali** [comment]
![微信图片_20240719094101](https://github.com/user-attachments/assets/0672a179-16fc-4331-9ba7-d79080e850ea)


报告导出来只能更新出十几个漏洞，这种情况应该怎么办呀？  求大佬们指点一下

**Comment by xiaogezainali** [comment]
@MatriX925
报告导出来只能更新出十几个漏洞，这种情况应该怎么办呀？  求大佬们指点一下

**Comment by xiaogezainali** [comment]
每次导出来的报告只能更新出17个 漏洞，这是怎么回事？求教！求教！求教！

**Comment by SmarTIGer** [comment]
@MatriX925 现在2025年6月了，可否再更新一下数据库？
