### ISSUE TITLE
请问以下报错如何解决

### ISSUE THREAD

**Issue by wangyan-samuel** [Hypdncy/NessusToReport#39]
Traceback (most recent call last):
  File "D:\NessusToReport-master\main.py", line 49, in <module>
    h.run()
  File "D:\NessusToReport-master\modle\handle.py", line 116, in run
    func_type_run[self.docxtype]()
  File "D:\NessusToReport-master\modle\handle.py", line 86, in run_loops
    DataLoops(self.LOOPHOLES).run()
  File "D:\NessusToReport-master\modle\data\loops.py", line 99, in run
    super(DataLoops, self).run()
  File "D:\NessusToReport-master\modle\data\base.py", line 92, in run
    self._gen_data_systems()
  File "D:\NessusToReport-master\modle\data\base.py", line 83, in _gen_data_systems
    system_host_names[str(row[0])] = str(row[1])
IndexError: list index out of range

**Comment by IM-HuangHui** [comment]
system.csv要是utf-8
