### ISSUE TITLE
求助报错信息

### ISSUE THREAD

**Issue by gloomytime** [Hypdncy/NessusToReport#46]
各位大佬这是个什么情况呀，我用的大佬最新的vuln.db

2024-05-08 15:49:44,230 - root - INFO - 开始初始化数据
2024-05-08 15:49:44,230 - root - INFO - ---开始读取数据
2024-05-08 15:49:44,380 - root - INFO - ----漏洞种类总数：328
2024-05-08 15:49:44,380 - root - INFO - ----漏洞主机总数：1
2024-05-08 15:49:44,380 - root - INFO - ---开始翻译数据
2024-05-08 15:49:44,381 - root - INFO - ------翻译漏洞总数：44
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/183232')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/183751')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/183410')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/183384')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/183750')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/182843')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/182891')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/182932')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/184161')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/184087')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/183834')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/186225')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/185342')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/186209')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/184303')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/186226')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/186711')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/186991')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/186676')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/187680')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/183889')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/187955')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/189915')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/189998')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/190689')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/190713')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/190598')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/190124')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/191663')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/191736')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/192404')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/192577')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/193082')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/193362')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/192219')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/193701')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/193596')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/191794')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/194950')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/194474')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/193905')
0, message='', url=URL('https://www.tenable.com/plugins/nessus/195135')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/190874')
0, message='', url=URL('https://www.tenable.com/plugins/nessus/193872')
Traceback (most recent call last):
  File "D:\pt\NessusToReport-1.2\main.py", line 48, in <module>
    h = Handle(args.docxtype, args.exceltype)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pt\NessusToReport-1.2\modle\handle.py", line 65, in __init__
    func_translate_tools[translate_tool](self.LOOPHOLES).run()
  File "D:\pt\NessusToReport-1.2\modle\common\translate\base.py", line 110, in run
    for plugin_id, resinfo in cn_resinfos:
        ^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

**Comment by gloomytime** [comment]
已解决，解决方法：
python -m pip install brotli
