### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by whitesharks** [Hypdncy/NessusToReport#47]
2024-05-09 12:36:02,101 - root - INFO - 开始初始化数据
2024-05-09 12:36:02,101 - root - INFO - ---开始读取数据
2024-05-09 12:36:02,109 - root - INFO - ----漏洞种类总数：13
2024-05-09 12:36:02,109 - root - INFO - ----漏洞主机总数：1
2024-05-09 12:36:02,109 - root - INFO - ---开始翻译数据
2024-05-09 12:36:02,111 - root - INFO - ------翻译漏洞总数：2
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/192466')
0, message='', url=URL('https://zh-cn.tenable.com/plugins/nessus/192568')
Traceback (most recent call last):
  File "D:\XX\NessusToReport\main.py", line 48, in <module>
    h = Handle(args.docxtype, args.exceltype)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\XX\NessusToReport\modle\handle.py", line 65, in __init__
    func_translate_tools[translate_tool](self.LOOPHOLES).run()
  File "D:\XX\NessusToReport\modle\common\translate\base.py", line 110, in run
    for plugin_id, resinfo in cn_resinfos:
        ^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

CSV文件是UTF-8的，麻烦看下，谢谢

**Comment by whitesharks** [comment]
已解决，是漏洞库没更新的原因。
更新了@MatriX925 的数据库，更新时间2024 年 4月 22 日。
链接: https://pan.baidu.com/s/1EbBAwrH-0QDatMRT9l6x8w?pwd=g9ub 提取码: g9ub

**Comment by whitesharks** [comment]
建议增加容错机制，在漏洞库没更新的情况下调用API翻译，翻译不成功则不翻译。
