### ISSUE TITLE
CSV报告存在域名导致转换失败

### ISSUE THREAD

**Issue by Be1Dsec** [Hypdncy/NessusToReport#55]
转换报告报错内容如下：
C:\Users\321\Desktop\NessusToReport-1.2>python main.py
2024-10-22 14:31:25,732 - root - INFO - 开始初始化数据
2024-10-22 14:31:25,732 - root - INFO - ---开始读取数据
Traceback (most recent call last):
  File "C:\Users\321\Desktop\NessusToReport-1.2\main.py", line 48, in <module>
    h = Handle(args.docxtype, args.exceltype)
  File "C:\Users\321\Desktop\NessusToReport-1.2\modle\handle.py", line 57, in __init__
    self.LOOPHOLES.run()
  File "C:\Users\321\Desktop\NessusToReport-1.2\modle\common\loophole\loopholes.py", line 185, in run
    self._get_init_nessus()
  File "C:\Users\321\Desktop\NessusToReport-1.2\modle\common\loophole\loopholes.py", line 105, in _get_init_nessus
    if IPy.IP(host) in IPy.IP(nessus_ignore_ip, make_net=True):
  File "E:\Python310\lib\site-packages\IPy.py", line 249, in __init__
    (self.ip, parsedVersion) = parseAddress(ip, ipversion)
  File "E:\Python310\lib\site-packages\IPy.py", line 1422, in parseAddress
    bytes = [int(x) for x in bytes]
  File "E:\Python310\lib\site-packages\IPy.py", line 1422, in <listcomp>
    bytes = [int(x) for x in bytes]
ValueError: invalid literal for int() with base 10: 'audit'
-------------------------------------------------------------------------------------
根据报错内容找了半天到底是哪里导致int()转换失败，后面发现由于Nessus扫描域名后CSV报告IP列是填写的域名，导致转换失败，但是使用旧版的工具是可以完成转换的，新版本不行？

**Comment by SmarTIGer** [comment]
修改根目录config.py文件，nessus_ignore_ips = [ ]这个地方为空即可解决。
